### ISSUE TITLE
canSeeCVs check no longer works

### ISSUE THREAD

**Issue by Rubio9** [userscripters/retrieveCVRVDV#52]
for canSeeCVs:
the element is now "js-close-question-link".

currently it thinks you don't have close vote privs even when you do.

**Comment by Rubio9** [comment]
thanks - any particular reason why the userscripters framework doesn't auto-generate the @downloadURL and @updateURL metadata comments?  this would allow Tampermonkey to follow your projects for updates without manual hassle.  (I was surprised I had to manually grab this update.)

**Comment by double-beep** [comment]
@Rubio9 sorry for the late reply. AFAIK, Tampermonkey *should* automatically update the script from the URL it was installed - `downloadURL`/`updateURL` shouldn't make any particular difference.
